// GENERATED by tools/gen-art.mjs — do not hand-edit.
// The ids listed here have a file at art/cards/<id>.webp. js/render.js paints a generated
// render for exactly these ids and falls back to RB.procArt (js/procart.js) for the rest.
window.RB = window.RB || {};
RB.artManifest = {
};
