#!/usr/bin/env node
// BreachForge card art generator — see docs/ART-PROMPT-RULES.md.
//
// Reads tools/art-prompts.json ({cardId: "one-line subject"}, committed, GENERATED by
// scratch/build-art-prompts.mjs — never hand-edited) and, for each id, sends
// `SUBJECT + ' ' + STYLE` to FLUX.1-schnell through the Hugging Face router, crops 8% off the
// bottom (the model signs its work there some of the time), re-encodes to WebP at q90, and writes
// art/cards/<id>.webp.
//
// The HTTP call, the crop and the WebP encode live in tools/lib/hf-image.mjs so a future board-art
// generator shares exactly the same pipeline. What lives HERE is the card-specific part: the STYLE
// constant, the prompt file, the art/cards/ layout, and the run plan.
//
// Billing is PREPAID — every generation costs real money. This tool is therefore idempotent by
// default (an id that already has art/cards/<id>.webp is skipped, never re-spent, unless --force)
// and --dry-run makes zero network calls.
//
// Usage:
//   node tools/gen-art.mjs --dry-run                  print the whole plan, generate nothing, free
//   node tools/gen-art.mjs --only ogn-027             generate exactly this id (exact match)
//   node tools/gen-art.mjs --limit 8                  generate at most 8 ids this run
//   node tools/gen-art.mjs --force --only ogn-027     regenerate even though art exists
//                                                       (archives the old file first)
//   node tools/gen-art.mjs --concurrency 5            override the default of 3 parallel requests
//   node tools/gen-art.mjs --token hf_xxx             pass the token directly (else HF_TOKEN env,
//                                                       else .hf_token / hf_token.md at the root)
//   node tools/gen-art.mjs --manifest-only            rebuild art/manifest.js from disk, nothing else
//
// Every run (including --dry-run) writes scratch/reports/gen-art-<date>.txt: generated / skipped /
// failed ids and why.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import {
  DEFAULTS, resolveToken, checkTools, generateToWebp, archiveExisting, asyncPool
} from './lib/hf-image.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const PROMPTS_PATH = path.join(ROOT, 'tools', 'art-prompts.json');
const ART_DIR = path.join(ROOT, 'art', 'cards');
// Superseded art goes to the gitignored art-archive/ at the repo root, alongside art-masters/ —
// the repo carries delivery WebP only.
const ARCHIVE_DIR = path.join(ROOT, 'art-archive');

// ---------------------------------------------------------------------------
// THE STYLE CONSTANT.
//
// Byte-identical on every single generation. This is the constant that makes 163 independently
// generated images read as one set — it is pasted verbatim into docs/ART-PROMPT-RULES.md, and if
// you change one character here you have started a new set and should regenerate all of them.
// ---------------------------------------------------------------------------
export const STYLE = 'Chibi super-deformed art direction throughout: every character, creature '
  + 'and figure has an oversized head atop a small compact body. Bold cel-shaded digital '
  + 'illustration with crisp highlights, confident linework and clean readable shapes; a '
  + 'saturated, vibrant colour palette; a wordless illustration, pure visual storytelling. The '
  + 'scene is a single full-bleed painted environment filling the frame edge to edge with rich '
  + 'background detail, sky or ground, depth and atmosphere — everything in the scene stands '
  + 'grounded within it, fully integrated into the setting. Dynamic lighting, dramatic rim light, '
  + 'strong value contrast between the subject and the light behind it. Vertical portrait '
  + 'composition, one cohesive artwork.';

function parseArgs(argv) {
  const opts = { dryRun: false, only: null, limit: Infinity, force: false, concurrency: 3, token: null, manifestOnly: false };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--dry-run') opts.dryRun = true;
    else if (a === '--only') opts.only = argv[++i];
    else if (a === '--limit') opts.limit = Number(argv[++i]);
    else if (a === '--force') opts.force = true;
    else if (a === '--concurrency') opts.concurrency = Number(argv[++i]);
    else if (a === '--token') opts.token = argv[++i];
    else if (a === '--manifest-only') opts.manifestOnly = true;
    else if (a === '--help' || a === '-h') opts.help = true;
    else { console.error(`Unknown flag: ${a}`); process.exit(1); }
  }
  return opts;
}

function loadPrompts() {
  if (!fs.existsSync(PROMPTS_PATH)) {
    console.error(`Missing ${path.relative(ROOT, PROMPTS_PATH)} — build it with `
      + 'node scratch/build-art-prompts.mjs');
    process.exit(1);
  }
  return JSON.parse(fs.readFileSync(PROMPTS_PATH, 'utf8'));
}

/**
 * Rebuild art/manifest.js from what is actually on disk. THIS FILE IS THE SWITCH: js/render.js
 * paints a generated image only for ids listed here and falls back to RB.procArt for everything
 * else, so a partial run is safe and a missing file can never produce a broken image. Rewritten at
 * the end of every run (and on demand with --manifest-only).
 */
export function writeManifest() {
  const prompts = fs.existsSync(PROMPTS_PATH) ? JSON.parse(fs.readFileSync(PROMPTS_PATH, 'utf8')) : {};
  const present = Object.keys(prompts).sort().filter(
    (id) => fs.existsSync(path.join(ART_DIR, `${id}.webp`))
  );
  // The board pipeline (tools/gen-board-art.mjs) lands its files in art/board/. Both switches
  // live in this one file so index.html has a single script tag to load.
  const boardDir = path.join(ROOT, 'art', 'board');
  const board = fs.existsSync(boardDir)
    ? fs.readdirSync(boardDir).filter((f) => f.endsWith('.webp')).map((f) => f.slice(0, -5)).sort()
    : [];
  const list = (arr) => (arr.length ? arr.map((id) => `  '${id}': 1`).join(',\n') + '\n' : '');
  const out = '// GENERATED by tools/gen-art.mjs — do not hand-edit.\n'
    + '// RB.artManifest: ids with a file at art/cards/<id>.webp. js/render.js paints a generated\n'
    + '// render for exactly these ids and falls back to RB.procArt (js/procart.js) for the rest.\n'
    + '// RB.boardArt: names with a file at art/board/<name>.webp, for the painted playmat areas in\n'
    + '// js/board.js. A name missing here simply does not paint, and the zone reads as before.\n'
    + 'window.RB = window.RB || {};\n'
    + `RB.artManifest = {\n${list(present)}};\n`
    + `RB.boardArt = {\n${list(board)}};\n`;
  const file = path.join(ROOT, 'art', 'manifest.js');
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, out);
  return { file, count: present.length, board: board.length };
}

function writeReport(lines) {
  const dir = path.join(ROOT, 'scratch', 'reports');
  fs.mkdirSync(dir, { recursive: true });
  const date = new Date().toISOString().slice(0, 10);
  const file = path.join(dir, `gen-art-${date}.txt`);
  fs.writeFileSync(file, lines.join('\n') + '\n');
  return file;
}

async function main() {
  const opts = parseArgs(process.argv.slice(2));
  if (opts.help) {
    console.log('See the header comment in tools/gen-art.mjs, or docs/ART-PROMPT-RULES.md.');
    return;
  }

  if (opts.manifestOnly) {
    const { file, count } = writeManifest();
    const { board } = writeManifest();
    console.log(`${count} card id(s) + ${board} board image(s) — wrote ${path.relative(ROOT, file)}`);
    return;
  }

  const prompts = loadPrompts();
  let ids = Object.keys(prompts).sort();

  if (opts.only) {
    if (!prompts[opts.only]) {
      console.error(`--only ${opts.only}: no such id in tools/art-prompts.json (exact match required)`);
      process.exit(1);
    }
    ids = [opts.only];
  }

  const plan = ids.map((id) => {
    const filePath = path.join(ART_DIR, `${id}.webp`);
    const exists = fs.existsSync(filePath);
    return { id, filePath, exists, action: exists && !opts.force ? 'skip' : 'generate' };
  });

  const toGenerate = plan.filter((p) => p.action === 'generate');
  const skippedExisting = plan.filter((p) => p.action !== 'generate').map((p) => p.id);
  const limited = Number.isFinite(opts.limit) ? toGenerate.slice(0, opts.limit) : toGenerate;
  const deferredByLimit = toGenerate.slice(limited.length).map((p) => p.id);

  if (opts.dryRun) {
    console.log('DRY RUN — no network calls, nothing written, nothing spent.');
    console.log(`${ids.length} id(s) in scope${opts.only ? ` (--only ${opts.only})` : ''}.`);
    console.log(`${skippedExisting.length} already have art/cards/*.webp (skip unless --force).`);
    console.log(`${limited.length} would be generated this run`
      + `${Number.isFinite(opts.limit) ? ` (--limit ${opts.limit})` : ''}:`);
    for (const p of limited) {
      const full = `${prompts[p.id]} ${STYLE}`;
      console.log(`  [${p.id}] ${full.length} chars: ${prompts[p.id]}`);
    }
    if (deferredByLimit.length) {
      console.log(`${deferredByLimit.length} more deferred by --limit: ${deferredByLimit.join(', ')}`);
    }
    const reportFile = writeReport([
      `gen-art dry-run ${new Date().toISOString()}`,
      `in scope: ${ids.length}`,
      `would generate: ${limited.map((p) => p.id).join(', ')}`,
      `already present (skip): ${skippedExisting.join(', ')}`,
      `deferred by --limit: ${deferredByLimit.join(', ')}`
    ]);
    console.log(`Report: ${path.relative(ROOT, reportFile)}`);
    return;
  }

  const missing = await checkTools();
  if (missing.length) {
    console.error(`Missing required CLI tool(s): ${missing.join(', ')}. `
      + '`sips` ships with macOS; install cwebp with `brew install webp`.');
    process.exit(1);
  }

  const token = resolveToken(ROOT, opts.token);
  if (!token) {
    console.error('No Hugging Face token: pass --token, set HF_TOKEN, or put one in a gitignored '
      + '.hf_token / hf_token.md at the repo root.');
    process.exit(1);
  }

  console.log(`${ids.length} id(s) in scope, ${skippedExisting.length} already have art, `
    + `${limited.length} to generate this run`
    + `${deferredByLimit.length ? ` (${deferredByLimit.length} deferred by --limit)` : ''}.`);

  const generated = [];
  const failed = [];
  const archived = [];

  await asyncPool(opts.concurrency, limited, async (p) => {
    try {
      if (p.exists && opts.force) {
        const dest = archiveExisting(p.id, p.filePath, ARCHIVE_DIR);
        archived.push(`${p.id} -> ${path.relative(ROOT, dest)}`);
      }
      const fullPrompt = `${prompts[p.id]} ${STYLE}`;
      const { bytes } = await generateToWebp(fullPrompt, token, p.filePath, DEFAULTS);
      generated.push(`${p.id} (${bytes} bytes)`);
      console.log(`OK   ${p.id}  ${bytes} bytes`);
    } catch (err) {
      failed.push(`${p.id}: ${err.message}`);
      console.error(`FAIL ${p.id}  ${err.message}`);
    }
  });

  console.log('');
  console.log(`Generated: ${generated.length}  Failed: ${failed.length}  `
    + `Skipped (already had art): ${skippedExisting.length}`
    + `${deferredByLimit.length ? `  Deferred by --limit: ${deferredByLimit.length}` : ''}`);

  const reportFile = writeReport([
    `gen-art run ${new Date().toISOString()}`,
    `concurrency: ${opts.concurrency}${opts.force ? '  --force' : ''}${opts.only ? `  --only ${opts.only}` : ''}`,
    '',
    `GENERATED (${generated.length}):`,
    ...generated.map((s) => `  ${s}`),
    '',
    `FAILED (${failed.length}):`,
    ...failed.map((s) => `  ${s}`),
    '',
    `SKIPPED — already had art (${skippedExisting.length}):`,
    ...skippedExisting.map((s) => `  ${s}`),
    '',
    `DEFERRED by --limit (${deferredByLimit.length}):`,
    ...deferredByLimit.map((s) => `  ${s}`),
    '',
    `ARCHIVED before overwrite (${archived.length}):`,
    ...archived.map((s) => `  ${s}`)
  ]);
  console.log(`Report: ${path.relative(ROOT, reportFile)}`);

  const manifest = writeManifest();
  console.log(`Manifest: ${path.relative(ROOT, manifest.file)} (${manifest.count} card id(s), ${manifest.board} board image(s))`);

  if (failed.length) process.exitCode = 1;
}

// Only run when invoked directly — tools/gen-board-art.mjs imports writeManifest from here.
if (import.meta.url === pathToFileURL(process.argv[1]).href) main();
